# Generated by Django 5.0.7 on 2024-08-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
