# Generated by Django 5.0.7 on 2024-08-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0013_alter_category_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
