# Generated by Django 5.1 on 2024-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0016_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
